spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: product-event-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.cqrs.*"
            type:
              mapping:
                productevent: org.cqrs.dto.ProductEvent
        spring.deserializer:
          value:
            delegate:
              class: org.springframework.kafka.support.serializer.JsonDeserializer